### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by talormanda** [RhythmLunatic/discord2groupme#1]
Im currently getting stuck doing these two steps. Can you elaborate how to do these from scratch?

- Install discord.js and request for node, then json and requests for python.
- Start discordhook with node and groupmehook with python.

I have node installed, and python also. (linux)

Also......how do you get the groupme user id?

**Comment by RhythmLunatic** [comment]
For node, It's just `npm install discord.js` and then `npm install request`
For python it's `pip3 install json` and `pip3 install requests`
And then start both with `python3 groupmehook.py` and then `node discordhook.js`

I don't remember how to get the groupme user ID, so now they're printed in the console if you don't have one set in config.json.

**Comment by talormanda** [comment]
@RhythmLunatic I am still lost. The steps required still need to be cleared up a little for me. I edited the config file and put all the info in minus my groupme user ID. I then opened up terminal and proceeded to type "npm install discord.js", and receive the following:

`pi@pi3_raspbian:~/discord2groupme-master $ npm install discord.js
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/discord2groupme-master/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/discord2groupme-master/package.json'
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord2groupme-master No description
npm WARN discord2groupme-master No repository field.
npm WARN discord2groupme-master No README data
npm WARN discord2groupme-master No license field.

+ discord.js@11.3.2
updated 1 package in 2.719s
`
Do you have any idea how to install the dependencies?

**Comment by RhythmLunatic** [comment]
It doesn't matter what order it's installed in. If the programs run then the install warnings can be ignored.

**Comment by talormanda** [comment]
@RhythmLunatic I am retrying this again right now. Standby lol.

**Comment by talormanda** [comment]
@RhythmLunatic here is what is holding me up. Maybe you can help,

`pi@pi3_raspbian:~/discord2groupme-master $ sudo python3 groupmehook.py 
No user ID set. Send a message and check this output for the user ID, then set it in config.json and restart.
Traceback (most recent call last):
  File "groupmehook.py", line 85, in <module>
    run()
  File "groupmehook.py", line 75, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
`

**Comment by RhythmLunatic** [comment]
You're using port 80 already, you need to use something else (or stop whatever service is currently using port 80)

You can specify a port as an argument, like `python3 groupmehook.py 1500` for port 1500. Then in the groupme dev settings the callback URL needs to be changed to use that port, it would then be something like http://coolsitehere.com:1500 or http://ip_address:1500

The port also needs to be open on your router or wherever you're hosting it, but that's outside the scope of this program and I can't help you with that.

**Comment by talormanda** [comment]
@RhythmLunatic Sorry to keep bothering you.

1. I get no user ID's in the console when I send a message
2. It does say "Go away!!" when I browse to the callback site

**Comment by talormanda** [comment]
@RhythmLunatic Okay I got it working. I see GroupMe chat messages in discord. So,
1. will there ever be a way to push discord messages back to GroupMe?
2. will it ever show the usernames from groupme on discord?

**Comment by talormanda** [comment]
@RhythmLunatic I still only see my messages. No one elses replies show up. Any suggestions?

**Comment by talormanda** [comment]
@RhythmLunatic I do see peoples messages on the terminal, just not in discord.

**Comment by RhythmLunatic** [comment]
Do you mean GroupMe to Discord?
If the GroupMe hook says 204 NO CONTENT it's working as intended, check your webhook.

**Comment by talormanda** [comment]
@RhythmLunatic - Okay. I can see messages from all users. The only thing I cannot do now is have messages FROM discord appear in groupme.

**Comment by RhythmLunatic** [comment]
I'm sorry, but I don't really have time to be debugging this issue any further.

You can try uncommenting the `console.log(response)` line at the bottom to see what the server is replying, but since I can't reproduce this issue it's not something I can fix.

**Comment by talormanda** [comment]
@RhythmLunatic Strangely enough I redownloaded the code and performed the setup as directed and now it seems to function. I do not understand. Your list of steps that describe what each line in the config is for is missing a few items and could be reworded clearer. You also might want to mention how to get your discord IDs by enabling dev settings in discord. You can also add that to get your groupme_user_id you can log into https://dev.groupme.com and click on "access token" on the top right and look for it. Just trying to help.
