### ISSUE TITLE
ERROR 202 null, callback URL?

### ISSUE THREAD

**Issue by Lordkarma88** [RhythmLunatic/discord2groupme#14]
In the discord.js window, every time I send a message in discord, it says:
`Lordkarma88 sent: test`
`ERROR 202 null`

Also, messages from Groupme don't get sent to Discord. I'm guessing I entered the wrong callback URL... What should it be? I entered the webhook link.

Thanks for the work.

**Comment by RhythmLunatic** [comment]
The callback URL in the groupme dev site is the URL and port of the computer you're running the groupme hook on. Ex: If you did `python3 groupmehook.py 666`, you would put something like `http://999.999.999:666`.

You put the discord callback url in config.json.

**Comment by Lordkarma88** [comment]
I see. So I can't use it on heroku, because I don't know their IP right?
I'll try doing that. By the way, I found a space in "groupme_token", so maybe that was the source of ERROR 202.

OK tried that and it didn't work... Still same problem.
Additionally, I've noticed the discord hook crashes after a few minutes, as soon as I send another message in discord. Here's a link to the error: https://pastebin.com/xFM0isXE.

When I try to connect to http://my-ip:9999, it doesn't find anything.

**Comment by RhythmLunatic** [comment]
I've updated the discord hook to not crash on an empty response so now you can tell what the error is.
Also an easy way to check if the port is open is to be running groupme hook and then try going to the ip + port in your browser. If it says connection refused then the port is either not open or the program isn't running.

**Comment by Lordkarma88** [comment]
Ok, now I get this:
`Bot has started, with 3 users, in 8 channels of 1 guilds.`
`LordКдЯМд88 sent: test`
`Error with no HTTP POST response: Error: getaddrinfo ENOTFOUND api.groupme.com api.groupme.com:443`
`LordКдЯМд88 sent: !ping`
`Error with no HTTP POST response: Error: getaddrinfo ENOTFOUND api.groupme.com api.groupme.com:443`
`LordКдЯМд88 sent: !ping`
`Groupme2Discord sent: Pong!`
`ERROR 202 null`
`ERROR 202 null`

I may have said it wrong before, when I try to go to the ip + port in my browser (https://my-ip:9999 in this case), it fails to connect, even though the program is running. 
Just checked something... If I enter 127.0.0.1:9999 it does say "Go away!!"

**Comment by RhythmLunatic** [comment]
`getaddrinfo ENOTFOUND` appears to be a DNS issue unrelated to the program. if https://api.groupme.com can't be accessed from your browser (it should redirect to the groupme home page) then you need to change or refresh your DNS.

If you cannot connect from your IP and port then you need to configure port forwarding. Which is still outside the scope of this program.
