### ISSUE TITLE
Messages from Groupme don't get sent to Discord

### ISSUE THREAD

**Issue by NSharker** [RhythmLunatic/discord2groupme#8]
Currently messages from my discord channel get posted onto the groupme chat.

However any messages from the groupme chat do not get posted onto the discord channel. 
I enter the command "sudo python3.6 groupmehook.py" and the console displays "HTTP server running on port 80".

Nothing else appears there. 

On the console that run node discordhook.js, i get the following warning:
(node:30255) DeprecationWarning: ClientUser#setGame: use ClientUser#setActivity instead
and then any messages from discord appear.

I'm not sure whats wrong with my set up.

**Comment by RhythmLunatic** [comment]
This issue is outside the scope of the program.

Did you forward port 80 so GroupMe could access your callback URL?

**Comment by NSharker** [comment]
Yeah I forwarded port 80. When I access my localhost:80, the browser shows Go away and I can see in the groupmehook terminal some activity. 

I think maybe my config file is incorrect.
I am unsure of what value the discord_id: should have in the config. Is it the client id of the bot or my personal own discord account id?

I also have allow_all : "true" so that any groupme user can respond back to the discord users. Does that mean I leave groupme_user_id as empty?

Sorry if I'm not asking in the appropriate place. Is there like a support forum or discord to get these questions answered?

**Comment by VBQL** [comment]
set your callback url in groupme to your server
